<?xml version="1.0" ?>
<robot name="leg_urdf" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="thigh_len" value="0.2" />
    <xacro:property name="calf_len" value="0.2" />
    <xacro:property name="thigh_radius" value="0.025"/>
    <xacro:property name="calf_radius" value="0.025"/>
		
	<material name="blue">
		<color rgba="0 0 1 1"/>
	</material>
	<material name="white">
		<color rgba="1 1 1 1"/>
	</material>
	
	<xacro:macro name="default_inertial" params="mass">
		<inertial>
            <mass value="${mass}" />
            <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
        </inertial>
    </xacro:macro>
    
	<!--Upper Leg -->
	<xacro:macro name="leg_macro" params="leg_name originxyz originrpy">
		<link name="${leg_name}thigh_link">
			<visual>
				<origin rpy="${-pi/2} 0 0" xyz="0 ${-thigh_len/2} 0"  />
				<geometry>
					<cylinder length="${thigh_len}" radius="${thigh_radius}"/>
				</geometry>
				<material name="blue"/>
        		</visual>
			<!--
			<collision>
			
			</collision>
			<inertial>
				<xacro:default_inertial mass="10" />
			</inertial> -->
		</link>
		<!--Hip Joint -->
		<joint name="base_link_to_${leg_name}thigh_link" type="revolute">
			<origin xyz="${originxyz}" rpy="${originrpy}" />
			<parent link="base_link" />
			<child link="${leg_name}thigh_link" />
			<axis xyz="0 0 1" />
			<limit effort="1000.0" lower="${-pi/3}" upper="${pi/3}" velocity="50"/>
		</joint>

		<link name="${leg_name}calf_link">
			<visual>
				<origin rpy="${-pi/2} 0 0" xyz="0 ${-calf_len/2} 0"  />
				<geometry>
					<cylinder length="${calf_len}" radius="${calf_radius}"/>
				</geometry>
				<material name="white"/>
        		</visual>
			<!--
			<collision>
			
			</collision>
			<inertial>
				<xacro:default_inertial mass="10" />
			</inertial> -->
		</link>
		<!--Hip Joint -->
		<joint name="${leg_name}thigh_link_to_${leg_name}calf_link" type="revolute">
			<origin xyz="0 ${-thigh_len} 0" rpy="0 0 0" />
			<parent link="${leg_name}thigh_link" />
			<child link="${leg_name}calf_link" />
			<axis xyz="0 0 1" />
			<limit effort="1000.0" lower="${-pi/3}" upper="${pi/3}" velocity="50"/>
		</joint>

	</xacro:macro>
	
</robot>
