# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

  # Position Controllers ---------------------------------------
BLLFT_controller:
  type: effort_controllers/JointPositionController
  joint: BLLFT
  pid: {p: 1.0, i: 0.0, d: 0.1}
LFTLFC_controller:
  type: effort_controllers/JointPositionController
  joint: LFTLFC
  pid: {p: 1.0, i: 0.0, d: 0.1}
BLLHT_controller:
  type: effort_controllers/JointPositionController
  joint: BLLHT
  pid: {p: 1.0, i: 0.0, d: 0.1}
LHTLHC_controller:
  type: effort_controllers/JointPositionController
  joint: LHTLHC
  pid: {p: 1.0, i: 0.0, d: 0.1}
BLRFT_controller:
  type: effort_controllers/JointPositionController
  joint: BLRFT
  pid: {p: 1.0, i: 0.0, d: 0.1}
RFTRFC_controller:
  type: effort_controllers/JointPositionController
  joint: RFTRFC
  pid: {p: 1.0, i: 0.0, d: 0.1}
BLRHT_controller:
  type: effort_controllers/JointPositionController
  joint: BLRHT
  pid: {p: 1.0, i: 0.0, d: 0.1}
RHTRHC_controller:
  type: effort_controllers/JointPositionController
  joint: RHTRHC
  pid: {p: 1.0, i: 0.0, d: 0.1}
